### ISSUE TITLE
Unable to launch  2.2.1. on Ubuntu 16.04

### ISSUE THREAD

**Issue by ncornelisse** [magkopian/keepassxc-debian#12]
After installing Keepassxc on Ubuntu 16.04 I can't launch it. It is probably not well installed, because there is no icon and can be found.

**Comment by magkopian** [comment]
Do you have the output of `dpkg` from when you installed the package?

**Comment by ju2wheels** [comment]
It installed fine for me. The icon may not show up until you reload you desktop environment (ALT+F2, r on Gnome shell) or log back in for others.

**Comment by magkopian** [comment]
I'm going to close this due to lack of input and since there doesn't seem to appear any issue with the package itself. @ncornelisse If your problem hasn't been resolved already and you still need help feel free to comment.
