### ISSUE TITLE
Provide hash and signature files for deb packages

### ISSUE THREAD

**Issue by petvoigt** [magkopian/keepassxc-debian#14]
Currently, downloaded deb packages cannot be verified with respect to integrity and origin. Please provide hash and signature files until there will be an official Debian PPA.

**Comment by magkopian** [comment]
The `deb` files already include hashes in them for every single file in the package, which `dpkg` automatically checks before installing the package. So, installing a corrupted package on your system is just not going to happen.

As for verifying the origin of the packages, this would make sense if the you downloaded them from a different source. But since the packages are already hosted on Github, I don't think there is any point doing that. Since if I provide any hashes they are going to be uploaded on Github as well.

**Comment by phoerious** [comment]
Have you tried adding the Ubuntu PPA? I haven't tested it, but it may work. See http://www.webupd8.org/2014/10/how-to-add-launchpad-ppas-in-debian-via.html

**Comment by magkopian** [comment]
Adding Ubuntu PPAs on Debian is a [really bad idea](https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian) and I highly recommend not even trying it. With that being said if you really want to try I can't stop you, but I take no responsibility if you break your system. 

Also remember that dependency problems sometimes take a bit to appear, so even if you have no issues at first you might get an unpleasant surprise the next you do updates. Finally, if you really want a third-party repository and you can't wait for KeePassXC to become part of the official Debian repositories, please feel free to share your opinion on issue #13.

**Comment by phoerious** [comment]
Our PPA offers no other packages than keepassxc (and libyubikey/yubikey-personalization for Trusty). So incompatible dependencies shoudn't be a problem.

**Comment by magkopian** [comment]
If there are no other repository added to the system from where apt can get the dependencies, I guess then worst thing that can happen is get an error about missing dependencies. If now it's a system where apt pinning is being used, I'm not so sure about the outcome.

In any case, I still won't recommend doing this unless you know exactly what you're doing and you are confident enough that in case you break something you can fix it.

**Comment by petvoigt** [comment]
I do not want to mess up my system with a Ubuntu PPA.

I have not been aware that every deb package does contain MD5 checksums that are being checked when the package is installed. Thanks for clarifying this point. Integrity of the package is at least ensured so far.

However, I do not understand why in your opinion a detached GPG signature does not help to check the origin of the deb packages. All I have learned so far is that this is just what a GPG signature is made for. In case of a hacked github repo you are currently not able to check the origin of the keepassxc deb files. And in this case it is of no value that the hash checks will pass ;-)

I do not remember every detail of the Linux Mint backdoor about one year ago where manipulated images have been placed on several mirrors. A detached GPG signature would have detected the manipulated images immediately and this is the reason why Linux Mint offers GPG signed SHA256 hashes.

My be I did not understand you correctly but I do really appreciate if you could provide either detached GPG signature files per deb package or SHA256 checksums of all deb files in one file which is GPG signed. Would this mean a lot of more effort in the role out process? A password safe is one of the most sensitive piece of software.

**Comment by magkopian** [comment]
@petvoigt The point I'm trying to make, is that in case of a hacked Github repository the signatures can be manipulated as well, because they'll also be provided via Github. A digital signature is only useful for verifying the origin of a file, if you are obtaining the file from a different source.

**Comment by petvoigt** [comment]
@magkopian: Sorry, but that is a basic missunderstanding of a GPG signature: It does NOT confirm the download location but the author of that file regardless from the used download mirror.

May be it is time to explicitly mention how I do appreciate your efforts to provide Debian packages of KeePassXC and I am willing to trust you as the author of theses packages. But I can do so only, if you provide GPG signatures of either each Debian package or - which can be achieved with less manual interaction - for a single file containing all e.g. sha256 checksums of all Debian packages.

All I can offer you to strengthen the reliability of you GPG key is to sign your public GPG key (among others) in the sense of the web of trust. In this case we just have to exchange the fingerprint of your key using a separate communication channel like e.g. email, Jabber or IRC. In this case you can contact me using me github email address.

**Comment by magkopian** [comment]
@petvoigt I did an attempt of signing one of the packages, you can download [here](https://github.com/magkopian/keepassxc-debian/files/1484673/keepassxc_2.2.2-1_amd64_stable_stretch.zip).

Once you download it and unzip it, you can test the signature by running the following two commands,

```
wget -O - https://agkopian.com/magkopian.gpg.key | apt-key add -
apt-key verify keepassxc_2.2.2-1_amd64_stable_stretch.deb
```

If everything went as expected, you should get an output similar to the following.

```
gpgv: Signature made Sat 18 Nov 2017 03:55:42 PM EET
gpgv:                using RSA key 0E2114884AA04C5AC9678C416B7EEADDCD254314
gpgv: Good signature from "Manolis Agkopian <m.agkopian@gmail.com>"
```

**Comment by phoerious** [comment]
I see @magkopian's point. You cannot trust the signature if you don't know it belongs to him. Sure, you can download the signature and will notice if the accounts gets hacked in the future, but if you download the signature from an already hacked account, there is no way for you to know if the signature was made with the correct key. The web of trust only solves this problem if you have actual trust anchors. Otherwise it's a chicken-egg problem.

**Comment by petvoigt** [comment]
@phoerious: Sure, therefore magkopian's key needs people confirming the key belongs to him - the basic idea of the Web of Trust. I have offered to do so, but need some identifying information about his key like the fingerprint which should be exchanged via a separate communication channel. This process of confirmation and subsequently signing a key is easier with people you can meet personally - this is what typically key signing parties are for.

**Comment by magkopian** [comment]
I have uploaded the key on my personal server, hosted under a `.com` domain which is my surname using a certificate from Let's Encrypt. Hopefully that will be enough, as long as people are aware that the `agkopian.com` domain is controlled by me.

**Comment by phoerious** [comment]
I don't think you can really establish trust here beyond verifying origin from a GitHub account and GitHub's own TLS certificate, unless you do meet in person. That makes the whole "ensure the GitHub account isn't hacked" thing a little dodgy. I think a GPG signature is good for verifying the authenticity of a file floating around somewhere, but it doesn't help much in the sense of trusting the integrity of @magkopian's GitHub account. TBH, that level of trust may already be enough for trusting the download, but it still relies on external factors which you can't fully verify.
That said, we have the same kind of trust anchor problem with our "official" KeePassXC key, but sign nevertheless (and we also sign with our PKI-verified Authenticode certificate, which I personally would trust even less, because all Comodo did was send us a plain-text email and ask us if we are ourselves).

**Comment by magkopian** [comment]
Honestly, the best thing you can do is clone the repository and compile the package yourself. I will start providing signed packages from this point forward, since it was requested and for me it just takes a few seconds to sign the packages. But apart from that, there isn't much else I can do. As @phoerious  pointed out, it's all a matter whether you trust my Github account at this point in time or not.

**Comment by petvoigt** [comment]
@magkopian: Thank you very much. The test package verification works as expected by you. However, I would have expected a detached signature file similar to https://github.com/keepassxreboot/keepassxc/releases/download/2.2.2/KeePassXC-2.2.2-2-x86_64.AppImage.sig. This would not have required you to rebuild the deb package.

Your key is not yet submitted to a keyserver and does not yet carry any signatures, while 
the official KeePassXC release key is hosted on the keyservers and carries several signatures hat everybody can inspect.

**Comment by magkopian** [comment]
@petvoigt I didn't have to rebuild the package, the process of signing a `deb` file is described [here](https://wiki.debian.org/DebianRepository/SetupWithReprepro) and it is done by using the `dpkg-sig` program. This is the proper of way of signing Debian binaries.

When you say to submit my key on a keyserver you mean to just fill out this form http://pool.sks-keyservers.net/?

**Comment by petvoigt** [comment]
@magkopian: Thank you for clarifying that the signature of a deb file does not require a rebuild. I have never build a deb package so far.

The form should do this but I have never used it so far. I usually use a command like:
gpg --keyserver  hkps://hkps.pool.sks-keyservers.net --send-key m.agkopian@gmail.com

If you have not configured your machine for hkps you can also use hkp://pool.sks-keyservers.net or any other keyserver URL e.g. like.

**Comment by magkopian** [comment]
@petvoigt I tried to submit the key using `gpg` but I got a `gpg: keyserver send failed: No route to host` error for some reason. But I then tried using the submission form [here](http://hkps.pool.sks-keyservers.net/) and it appears that it worked. If you search for my name now you should be able to find the key.

**Comment by petvoigt** [comment]
@magkopian: Your key has arrived on the keyserver and is being synced to the other keyserver.

Referring to your error message: did you use hkps://hkps.pool.sks-keyservers.net  or hkp://pool.sks-keyservers.net?

**Comment by magkopian** [comment]
@petvoigt I did receive your email and I was able to decrypt it using my key with the Enigmail addon for Thunderbird, but I'm having a bit of trouble responding to it. Every time I click the "Send" button it just says sending and it take for ever, I'm not sure what is going on.

Anyway, the contents of your email were the following, if you want to verify that I can actually decrypt the email,

```
Hi Manolis,

after some discussion yesterday and today on Github I have received your
public GPG key. Would you like me to sign your public key?

Regards,
Peter
```

As for your question I tied both of them, the result was the same.

**Comment by petvoigt** [comment]
@magkopian: In order to reply encrypted you will have to import my key to your GPG keyring first: KeyID is 0x1CA1C3A9.

**Comment by magkopian** [comment]
@petvoigt I tried that, but every time I click the "Import" button I get the error "We are sorry, could not find any key that would match the specified search criteria.". Maybe there is some kind of issue with the addon, I don't know I've never used it before to be honest.

**Comment by petvoigt** [comment]
@magkopian, Enigmal/Thunderbird generally works though I use Claws Mail most of the time. To exclude any problems with Enigmail/Thunderbird you could try:
gpg --keyserver hkp://pool.sks-keyservers.net --recv-key 0x1CA1C3A9

This adds my public key to your keyring. Enigmail just reads the same keyring.

**Comment by magkopian** [comment]
I've updated the binary packages attached on the current release with their signed versions. I also updated the release notes, to include instructions on how to verify a package. So, I think I can now go ahead the close this issue. If anyone wants to add something to the discussion though, please feel free.
