### ISSUE TITLE
Download favicon does not work in a proxy environment

### ISSUE THREAD

**Issue by eckhbeck** [magkopian/keepassxc-debian#15]
Clicking the 'Download favicon' throws an error message (Unable to fetch favicon) when a proxy server is required to access the URL of an entry. The same entry does work perfectly in an environment where no proxy is required.

**Comment by magkopian** [comment]
Is the issue related to the Debian package specifically, or it applies to the Snap and the AppImage as well?

**Comment by eckhbeck** [comment]
Oops, guess I opened the issue in the wrong place. I'm sure this problem is not "debian packaging" related. Sorry for this!
