### ISSUE TITLE
Hotkeys not working if toolbar isn't visible with Ubuntu 14.04 trusty (works with 16.04)

### ISSUE THREAD

**Issue by user240** [magkopian/keepassxc-debian#16]
I installed the latest 

> keepassxc_2.2.4-0ppa1~trusty1_amd64.deb

(and also tested with "keepassxc_2.2.2-1~trusty3_amd64.deb")
from
https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+packages

If the toolbar is not visible (Menu "View", "Show toolbar" not checked) all Hotkeys won't work.
The hotkey ctrl+q never works.

**Comment by magkopian** [comment]
It should be noted that I'm not the one responsible for the Ubuntu PPA and any issues related to the packages provided by it, should be brought to the attention of the KeePassXC upstream developers by opening an issue [here](https://github.com/keepassxreboot/keepassxc/issues).

**Comment by user240** [comment]
Yes I tested the AppImage from https://keepassxc.org/download#linux
and the hotkeys seems to work correctly with AppImage.

I wrote an e-mail to: <a href="https://launchpad.net/~phoerious">Janek Bevendorff</a>
for asking where to report a bug for Ubuntu 14.04 *.deb package.
