### ISSUE TITLE
Pushing the Power-Off Button closes the window but doesn't quit the program (Ubuntu 14.04 trusty, works with 16.04)

### ISSUE THREAD

**Issue by user240** [magkopian/keepassxc-debian#17]
Pushing the "Power-Off" Button from the computer, closes the programs window but doesn't quit the program/process. KeePassXC must be terminated by system-monitor (taskman) before it could be started again.

**Comment by magkopian** [comment]
As mentioned on #16 I'm not the one responsible for the Ubuntu PPA and the packages provided by it. Also, please make sure to verify whether the problem is related to the package itself or not. Please try running KeePassXC from the AppImage and see if the same problem still occurs.

**Comment by user240** [comment]
Created a new issue:<a href="/keepassxreboot/keepassxc/issues/1287" class="link-gray-dark no-underline h4 js-navigation-open">
        Pushing the Power-Button from the computer closes the window but doesn't quit the program with Ubuntu 14.04 trusty (works with 16.04)
      </a>
