### ISSUE TITLE
Debian 32 bit build failed

### ISSUE THREAD

**Issue by srkn** [magkopian/keepassxc-debian#18]
Hi, 
I could not run this on a debian 32 bit machine, I downloaded this filekeepassxc_2.3.3-1_i386_stable_stretch.deb , I attempted to make it work several times but no chance. Which depedencies I need to install for this?

**Comment by magkopian** [comment]
If your problem is related to missing dependencies, you should be able to fix that by running `apt install -f` as root. What happens when you try to run the program exactly? Do you get an error message?

**Comment by magkopian** [comment]
@srkn I'm assuming that you managed to fix your issue since it's been already two days and I've go no reply. I'm going to close this issue for now, but if you're still have problems just reply here and I'll reopen it.
