### ISSUE TITLE
KeePassXC 2.5.1 for Debian Stretch

### ISSUE THREAD

**Issue by dstrelnikov** [magkopian/keepassxc-debian#19]
Hello!

Can I candly ask you to build a package for the last KeePass XC version?

**Comment by magkopian** [comment]
KeePassXC is officially maintained by the Debian Project for quite some time now so I have stopped maintaining this package. I see that `testing` is currently on `2.4.3` so it should arrive on `stretch-backports` shortly, as for `2.5.1` that will probably take a while.

**Comment by dstrelnikov** [comment]
Okay, thank you for the information!
