### ISSUE TITLE
Provide 32 bit .deb packages

### ISSUE THREAD

**Issue by mkasberg** [magkopian/keepassxc-debian#5]
How difficult would it be to provide 32 bit .deb packages?

Based on some quick reading I've done, it looks like it can be done with `--architecture i386` arg to `pbuilder --create`.

**Comment by magkopian** [comment]
The reason I wasn't providing 32-bit binaries until now, was simply that compiling takes time and no one had requested it. Anyway, I've just build [32-bit binaries](https://github.com/magkopian/keepassxc-debian/files/958243/keepassxc_2.1.4-1_i386.tar.gz) for the latest version, so would you mind testing them before I upload them on the releases page?

**Comment by mkasberg** [comment]
Sure! I'll try them out later today when I get home. Thanks for the quick response! And thanks for building this project into Debian packages - I'm already using your 64 bit builds.

**Comment by mkasberg** [comment]
Tested on a 32-bit machine. Works great!

**Comment by magkopian** [comment]
Nice, thanks for the help!
