### ISSUE TITLE
Please support old-stable.

### ISSUE THREAD

**Issue by danwep** [magkopian/keepassxc-debian#6]
Hello,

First Thank You very much for creating these KeePassXC packages. Some of us wait a long time, before moving to the new stable[about a year in my case]. Would appreciate creating old-stable packages for as long as old-stable is officially supported; a year. For newer KeePassXC releases, since keepassxc_2.1.4-1_amd64_stable.deb installs fine in old-stable.

Thank You and Be Well

**Comment by magkopian** [comment]
No, problem, as long as there is interest it will. The `keepassxc_2.1.4-1_amd64_stable.deb` package of the last release works on the current Oldstable, as the release was before Stretch became the new Stable. From the next package release though, that issue will be resolved.

**Comment by danwep** [comment]
Yes, indeed the current keepassxc_2.1.4-1_amd64_stable.deb installs fine in old-stable. Great and Thank You for the quick reply and your work on these KeePassXC packages.

Be Well
